-- Tắt kiểm tra khóa ngoại để tránh lỗi khi drop
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS BookingService;
DROP TABLE IF EXISTS Booking;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS RoomPrice;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS RoomStatus;
DROP TABLE IF EXISTS TypeRoom;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS HotelBranch;

DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS HistoryLogin;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Countries;
DROP TABLE IF EXISTS Genders;

DROP TABLE IF EXISTS Notification;
DROP TABLE IF EXISTS NotificationStatus;
DROP TABLE IF EXISTS Conversation;
DROP TABLE IF EXISTS Message;

DROP TABLE IF EXISTS Report;
DROP TABLE IF EXISTS ReportType;
DROP TABLE IF EXISTS Maintenance;
DROP TABLE IF EXISTS Review;

DROP TABLE IF EXISTS CheckIn;
DROP TABLE IF EXISTS CheckOut;
DROP TABLE IF EXISTS Receipt;

-- Bật lại kiểm tra khóa ngoại
SET FOREIGN_KEY_CHECKS = 1;
