CREATE TABLE IF NOT EXISTS services(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL UNIQUE,
    description TEXT ,
    price BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS hotelbranch(
    id INT PRIMARY KEY AUTO_INCREMENT,
    address VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(30) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS roles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    role_name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS countries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(3) NOT NULL UNIQUE,
    country_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE Table IF NOT EXISTS locations(
    id INT PRIMARY KEY AUTO_INCREMENT,
    location VARCHAR(50) NOT NULL UNIQUE
);

CREATE Table IF NOT EXISTS typeroom(
    id INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    gender_name VARCHAR(20) NOT NULL UNIQUE
);

CREATE Table IF NOT EXISTS roomstatus(
    id INT PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(30) NOT NULL UNIQUE
);

CREATE Table IF NOT EXISTS reporttype(
    id INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(30) NOT NULL UNIQUE
);

CREATE Table IF NOT EXISTS notificationstatus(
    id INT PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS room(
    id INT PRIMARY KEY AUTO_INCREMENT,
    area VARCHAR(30) NOT NULL,
    number_of_bed INT NOT NULL,
    description TEXT NOT NULL,
    room_img TEXT NOT NULL,
    hotel_branch_id INT,
    type_room_id INT ,
    location_id INT ,
    room_status_id INT ,
    CONSTRAINT fk_room_HotelBranch_id FOREIGN KEY (hotel_branch_id) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_room_TypeRoom_id FOREIGN KEY (type_room_id) REFERENCES typeroom(id)  ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_room_Location_id FOREIGN KEY (location_id) REFERENCES locations(id)  ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_room_RoomStatus_id FOREIGN KEY (room_status_id) REFERENCES roomstatus(id)  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS booking(
    id INT PRIMARY KEY AUTO_INCREMENT,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    booked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    room_img TEXT NOT NULL,
    hotel_branch_id INT,
    room_id INT,
    CONSTRAINT fk_booking_HotelBranch_id FOREIGN KEY (hotel_branch_id) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_booking_room_id FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE SET NULL ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS bookingservice(
    Type_roomID INT ,
    ServiceID INT ,
    CONSTRAINT fk_bookingService_typeRoom_id FOREIGN KEY (Type_roomID) REFERENCES typeroom(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_bookingService_service_id FOREIGN KEY (ServiceID) REFERENCES services(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(50) UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    full_name VARCHAR(100),
    date_of_birth DATE,
    gender_id INT,
    phone_number VARCHAR(20),
    current_address VARCHAR(255),
    country_id INT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until DATETIME NULL,
    last_login_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_users_gender FOREIGN KEY (gender_id) REFERENCES genders(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_users_country FOREIGN KEY (country_id) REFERENCES countries(id)
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS staff(
    id INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    HotelBranchID INT ,
    CONSTRAINT fk_staff_user FOREIGN KEY (UserID) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_staff_branch FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id)
         ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS historylogin(
    id INT PRIMARY KEY AUTO_INCREMENT,
    timeLogin TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL ,
    CONSTRAINT fk_historyLogin_user_id FOREIGN KEY (UserID) REFERENCES users(id)  ON DELETE CASCADE  ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS roomprice(
    id INT PRIMARY KEY AUTO_INCREMENT,
    dateStart DATE NOT NULL,
    dateEnd DATE NOT NULL,
    price BIGINT NOT NULL,
    HotelBranchID INT ,
    RoomID INT ,
    CONSTRAINT fk_roomPrice_HotelBranch_id FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_roomPrice_Room_id FOREIGN KEY (RoomID) REFERENCES room(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE Table IF NOT EXISTS notificationstatus(
    id INT PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS room(
    id INT PRIMARY KEY AUTO_INCREMENT,
    area VARCHAR(30) NOT NULL,
    numberOfBed INT NOT NULL,
    description TEXT NOT NULL,
    roomIMG TEXT NOT NULL,
    HotelBranchID INT,
    TypeRoomID INT ,
    LocationID INT ,
    RoomStatusID INT ,
    CONSTRAINT fk_room_HotelBranch_id FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_room_TypeRoom_id FOREIGN KEY (TypeRoomID) REFERENCES typeroom(id)  ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_room_Location_id FOREIGN KEY (LocationID) REFERENCES locations(id)  ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_room_RoomStatus_id FOREIGN KEY (RoomStatusID) REFERENCES roomstatus(id)  ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS booking(
    id INT PRIMARY KEY AUTO_INCREMENT,
    checkInDate DATE NOT NULL,
    checkOutDate DATE  NOT NULL,
    bookedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    roomIMG TEXT NOT NULL,
    HotelBranchID INT ,
    RoomID INT ,
    CONSTRAINT fk_booking_HotelBranch_id FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_booking_room_id FOREIGN KEY (RoomID) REFERENCES room(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bookingservice(
    Type_roomID INT ,
    ServiceID INT ,
    CONSTRAINT fk_bookingService_typeRoom_id FOREIGN KEY (Type_roomID) REFERENCES typeroom(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_bookingService_service_id FOREIGN KEY (ServiceID) REFERENCES services(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(50) UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    full_name VARCHAR(100),
    date_of_birth DATE,
    gender_id INT,
    phone_number VARCHAR(20),
    current_address VARCHAR(255),
    country_id INT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_login_attempts INT NOT NULL DEFAULT 0,
    locked_until DATETIME NULL,
    last_login_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_users_gender FOREIGN KEY (gender_id) REFERENCES genders(id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_users_country FOREIGN KEY (country_id) REFERENCES countries(id)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS staff(
    id INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    HotelBranchID INT ,
    CONSTRAINT fk_staff_user FOREIGN KEY (UserID) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_staff_branch FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id)
         ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS historylogin(
    id INT PRIMARY KEY AUTO_INCREMENT,
    timeLogin TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL ,
    CONSTRAINT fk_historyLogin_user_id FOREIGN KEY (UserID) REFERENCES users(id)  ON DELETE CASCADE  ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS roomprice(
    id INT PRIMARY KEY AUTO_INCREMENT,
    dateStart DATE NOT NULL,
    dateEnd DATE NOT NULL,
    price BIGINT NOT NULL,
    HotelBranchID INT ,
    RoomID INT ,
    CONSTRAINT fk_roomPrice_HotelBranch_id FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_roomPrice_Room_id FOREIGN KEY (RoomID) REFERENCES room(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS notification(
    id INT PRIMARY KEY AUTO_INCREMENT,
    message TEXT NOT NULL,
    createAt DATETIME NOT NULL,
    isBroadcast BOOLEAN NOT NULL,
    UserID INT NOT NULL,
    NotificationStatusID INT,
    CONSTRAINT fk_notification_user_id FOREIGN KEY (UserID) REFERENCES users(id) ON DELETE CASCADE  ON UPDATE CASCADE,
    CONSTRAINT fk_notification_status_id FOREIGN KEY (NotificationStatusID) REFERENCES notificationstatus(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS conversation(
    id INT PRIMARY KEY AUTO_INCREMENT,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status varchar(30) NOT NULL,
    CustomerID INT NOT NULL,
    HotelBranchID INT ,
    CONSTRAINT fk_conversation_customer_id FOREIGN KEY (CustomerID) REFERENCES users(id) ON DELETE  CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_conversation_hotelBranch_id FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS report(
    id INT PRIMARY KEY AUTO_INCREMENT,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL,
    periodStart DATE NOT NULL,
    periodEnd DATE NOT NULL,
    createBy INT NOT NULL,
    HotelBranchID INT ,
    reportTypeID INT,
    CONSTRAINT fk_report_customer_id FOREIGN KEY (createBy) REFERENCES users(id) ON DELETE CASCADE  ON UPDATE CASCADE,
    CONSTRAINT fk_report_hotelBranch_id FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_report_reportType_id FOREIGN KEY (reportTypeID) REFERENCES reporttype(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS maintenance(
    id INT PRIMARY KEY AUTO_INCREMENT,
    description TEXT NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    RoomID INT NOT NULL UNIQUE,
    HotelBranchID INT,
    StaffID INT NOT NULL,
    CONSTRAINT fk_maintenance_room_id FOREIGN KEY (RoomID) REFERENCES room(id) ON DELETE CASCADE  ON UPDATE CASCADE,
    CONSTRAINT fk_maintenance_hotelBranch_id FOREIGN KEY (HotelBranchID) REFERENCES hotelbranch(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_maintenance_staff_id FOREIGN KEY (StaffID) REFERENCES staff(id) ON DELETE  CASCADE ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS review(
    id INT PRIMARY KEY AUTO_INCREMENT,
    comment TEXT ,
    rating INT NOT NULL,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CustomerID INT NOT NULL,
    BookingID INT ,
    CONSTRAINT fk_review_customer_id FOREIGN KEY (CustomerID) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_review_booking_id FOREIGN KEY (BookingID) REFERENCES booking(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS checkin(
    id INT PRIMARY KEY AUTO_INCREMENT,
    checkInTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    StaffID INT NOT NULL,
    BookingID INT ,
    CONSTRAINT fk_checkIn_staff_id FOREIGN KEY (StaffID) REFERENCES staff(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_checkIn_booking_id FOREIGN KEY (BookingID) REFERENCES booking(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS checkout(
    id INT PRIMARY KEY AUTO_INCREMENT,
    checkOutTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    StaffID INT NOT NULL,
    BookingID INT,
    CONSTRAINT fk_checkOut_staff_id FOREIGN KEY (StaffID) REFERENCES staff(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_checkOut_booking_id FOREIGN KEY (BookingID) REFERENCES booking(id) ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS receipt(
    id INT PRIMARY KEY AUTO_INCREMENT,
    paymentMethod varchar(30) NOT NULL,
    amount INT NOT NULL,
    paymentDate DATE NOT NULL,
    BookingID INT ,
    CONSTRAINT fk_receipt_booking_id FOREIGN KEY (BookingID) REFERENCES booking(id)  ON DELETE SET NULL ON UPDATE CASCADE

);

CREATE TABLE IF NOT EXISTS message(
    id INT PRIMARY KEY AUTO_INCREMENT,
    content TEXT NOT NULL,
    sentAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ConversationID INT ,
    SenderID INT NOT NULL,
    CONSTRAINT fk_message_conversation_id FOREIGN KEY (ConversationID) REFERENCES conversation(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_message_sender_id FOREIGN KEY (SenderID) REFERENCES users(id)  ON DELETE  CASCADE ON UPDATE CASCADE

);